### ISSUE TITLE
Wrong page number in index entries like `\keywords`

### ISSUE THREAD

**Issue by muzimuzhi** [josephwright/beamer#547] opened 2019-09-07 12:07 UTC
The formal intro of `\keywords` appears on page 95, but in index part, its related page is shown as 90.
Several other index entries have this same problem, for example class option `usepdftitle`.

**Comment by louisstuart96** [comment] 2019-09-07 12:51
Maybe it's related to #540?
Edit: Confirmed. Since it has been fixed in e6a8fb7, this issue will be closed.

**Closed as completed** 2019-09-07 13:11 UTC
