### ISSUE TITLE
beamerarticle breaks \\

### ISSUE THREAD

**Issue by ax006ho** [josephwright/beamer#586] opened 2020-03-11 22:15 UTC
The attached file
[titelei_mwe.tex.zip](https://github.com/josephwright/beamer/files/4321183/titelei_mwe.tex.zip)
 can be processed by pdflatex without any problem.

If the out-commented \usepackage{beamerarticle} (v3.57) 

is activated, the result is quite curious: no line break, but "[1cm]" is printed between a and b

This can be remedied by removing the % at the beginning of lines 4-6.

The problem doesn't exist with beamer v3.55

**Comment by samcarter** [comment] 2020-03-11 22:24
sounds like https://github.com/josephwright/beamer/issues/582

**Comment by josephwright** [comment] 2020-03-11 22:24
Duplicate of #582

**Closed as completed** 2020-03-11 22:24 UTC
Labels: bug, duplicate
