### ISSUE TITLE
Overfull warning caused by nested beamercolorbox with 'sep' or 'colsep' settings

### ISSUE THREAD

**Issue by louisstuart96** [josephwright/beamer#364] opened 2017-01-26 03:36 UTC
Using the latest `beamer` class [2017/01/22 v3.40].
MWE:
```
\documentclass[10pt]{beamer}
\usepackage[T1]{fontenc}
\begin{document}
\setbeamercolor{testbox}{bg=blue!40!black,fg=white}
\setbeamercolor{testinbox}{bg=blue,fg=white}
\begin{frame}
\begin{beamercolorbox}[wd=0.5\textwidth,sep=4pt]{testbox}
Test box\par
\begin{beamercolorbox}[wd=0.3\textwidth,sep=7pt]{testinbox}
Test box
\end{beamercolorbox}
\end{beamercolorbox}\par
\end{frame}
\end{document}
```
Log says "Overfull \hbox (8.0pt too wide) in paragraph at lines ...", seemed like the outer colorbox is overfull due to "sep=4pt", but I can't make it from `\showlists`. The output looks no signs of bad boxes.

**Comment by josephwright** [comment] 2017-01-31 09:09
Goes all the way back to at least v3.06 (where Vedran and I picked up from Till).

**Comment by josephwright** [comment] 2017-01-31 09:42
Looks like https://github.com/josephwright/beamer/issues/352 to me: the problematic code is
```latex
      \leftskip=\beamer@colbox@ls%
      \advance\leftskip by\beamer@colbox@sep%
```
I've not got to this bit just yet on the 'sweep' I'm doing of the codebase (the box stuff is by far the most tricky), but I'd expect this issue to get fixed along with others in the area.

I'll mark as a dupe of the earlier bug unless there's a reason to look at this separated (adding `\@arrayparboxrestore` does seem to do the job: I'm just worried about the knock-on effects!).

**Closed as completed by josephwright** 2017-01-31 09:42 UTC
Labels: bug, duplicate

**Comment by louisstuart96** [comment] 2017-01-31 10:33
I've checked the result of `\showlists` log again. The addition of `\leftskip` and `\rightskip` will influence this box in inner `beamercolorbox`:
```
% line 211
      \if@tempswa\setbox\beamer@tempbox=\hbox{\vbox{%
```

**Comment by josephwright** [comment] 2017-01-31 10:34
Yes, I can see where the issue's arising from: as I say, Frank's pointed out that there is a general issue in this regard.
