### ISSUE TITLE
(Doc) Overview of class options

### ISSUE THREAD

**Issue by titanic-jb** [josephwright/beamer#688] opened 2021-05-29 06:51 UTC
I would love to have a section in the manual, describing the options for the beamer class.

I think, part I "Getting Started" or Part II "Building a Presentation" could be good point for insertion.

I personally would drop it in directly beneath \part{Building a Presentation} as a new \chapter{Loading the class}.

I found these class options, by searching the manual for the string `\documentclass[`:

- `color=⟨list of options⟩`
- `foils`
- `hyperref=⟨list of options⟩`
- `ucs`
- `utf8x`
- `utf8`
- `xcolor=⟨list of options⟩`
- `dvips`
- `draft`
- `compress`
- `t`
- `c`
- `aspectratio=1610`
- `aspectratio=169`
- `aspectratio=149`
- `aspectratio=141`
- `aspectratio=54`
- `aspectratio=43`
- `aspectratio=32`
- `usepdftitle=false`
- `envcountsect`
- `notheorems`
- `noamsthm`
- `noamssymb`
- `leqno`
- `fleqn`
- `8pt`
- `9pt`
- `10pt`
- `smaller`
- `11pt`
- `12pt`
- `bigger`
- `14pt`
- `17pt`
- `20pt`
- `trans`
- `handout`
- `ignorenonframetext`
- `notes`

This could be a good opportunity, to add them also into the index.  You find a entry `Beamer options` but none of the above is listed in that section.  There is no other option-keyword in the index present.

**Comment by samcarter** [comment] 2021-06-08 14:59
sounds like a duplicate of #578

**Closed as completed by samcarter** 2021-06-08 14:59 UTC
Labels: duplicate, enhancement
