### ISSUE TITLE
Wrong eps to pdf conversion under beamer using pstools

### ISSUE THREAD

**Issue by MaltiRachid** [josephwright/beamer#773] opened 2022-05-25 21:27 UTC
This issue was first described [here](https://tex.stackexchange.com/questions/645153/wrong-eps-to-pdf-conversion-under-beamer-using-pstools?noredirect=1#comment1607731_645153) with no proposed fix or workaround. 

When converting, under _beamer documentclass_, an eps file to a pdf file using \fragfig command from the pstool package, the generated pdf file takes the whole beamer background and its size is corrupted which is NOT desired.

In the minimum (non-) working example shown below, the eps-file _ExampleFig.eps_ is converted to _ExampleFig.pdf_ and yields the following file with a wrong size and the footline from beamer, which is NOT desired.
<img width="440" alt="image" src="https://user-images.githubusercontent.com/78661204/170369579-96b9ff04-3c52-4df9-bffc-1e22c5671b65.png">

By changing the documentclass to article the CORRECT pdf file is generated (as in the image below).

<img width="233" alt="image" src="https://user-images.githubusercontent.com/78661204/170369643-9e20a136-27ee-486b-b516-f180acede5b2.png">

Note that I'm talking about eps to pdf conversion and not about the global tex to pdf!

Is it the right place for posting the issue? Is it rather related to the pstool package? Anyway, to the best of my knowledge this issue appears only when using _beamer document class_.

Below is the minimum example. The eps file can be downloaded from [here](https://malti.fr/images/ExampleFigeps.zip) and unzipped in the same directory.

```
 \documentclass{beamer}
 %\documentclass{article}
 \usepackage[crop=pdfcrop,process=all]{pstool} 
 \begin{document}
     \begin{figure}[h!]
         \centering
         \psfragfig[scale=0.2]{ExampleFig}{
         \psfrag{AB}[][r]{\scalebox{1}{$G(p)$}}          
         }  
     \end{figure}
  \end{document}
```

**Comment by samcarter** [comment] 2022-05-25 21:43
Check if the problem also occurs if you add the mandatory `frame` environment.

Can you please add

- your .log file
- which command do you use to compile your document

**Comment by samcarter** [comment] 2022-05-25 21:46
might be a duplicate of https://github.com/wspr/pstool/issues/23

**Comment by samcarter** [comment] 2022-05-25 21:53
The pstools documentation has the following to say in `5.1 Conditional preamble or setup commands`

<img width="692" alt="Screenshot 2022-05-25 at 23 52 29" src="https://user-images.githubusercontent.com/43832342/170373515-81cc6ddf-b8d6-4198-8b2a-3d90c3f14cef.png">

**Comment by samcarter** [comment] 2022-05-25 22:10
This seems to work fine:

```
% !TeX program = txs:///arara
% arara: pdflatex: {synctex: on, interaction: nonstopmode, shell: yes}

 \documentclass{beamer}
 
  \ifpdf\else
          \setbeamertemplate{navigation symbols}{}
 \fi
 

 \usepackage[crop=pdfcrop,process=all]{pstool} 
 \begin{document}
 \begin{frame}
     \begin{figure}
         \psfragfig[scale=0.2]{ExampleFig}{
         \psfrag{AB}[][r]{\scalebox{1}{$G(p)$}}          
         }  
     \end{figure}
   \end{frame}
  \end{document}
```

![document](https://user-images.githubusercontent.com/43832342/170375726-401b94a3-c991-4530-bbeb-6ecd17510605.png)

**Closed as completed by samcarter** 2022-05-25 22:10 UTC

**Comment by MaltiRachid** [comment] 2022-05-26 14:37
Thank you very much @samcarter. I had also another issue, that did not appear in the MWE, linked to the background image. So I just adapted your code. Thanks again.
  
>  \ifpdf
  >  	\setbeamertemplate{background canvas}{%
  >     		\includegraphics[width=\paperwidth,height=\paperheight]{my_background_image}  
  > 	}
  >  \else
 >           \setbeamertemplate{navigation symbols}{}
  >           \setbeamertemplate{background canvas}{}
>  \fi
